name: Build for Fedora Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: fedora:41

    steps:
      - name: Install deps
        run: yum install autoconf automake bzip2 bzip2-devel cmake freetype-devel gcc gcc-c++ git libtool make pkgconfig zlib-devel git man-pages asciidoc docbook-dtds man-db xmlto -y
      - name: Download NASM
        run: cd ~/ && git clone https://github.com/netwide-assembler/nasm
      - name: Install NASM
        run: cd ~/nasm && ./autogen.sh && ./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" && make && make all nasm.1 ndisasm.1 && make install
      - name: Download YASM
        run: cd ~/ && git clone https://github.com/yasm/yasm
      - name: Install YASM
        run: cd ~/yasm && ~/yasm/configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" && make && make install
